# Generated by Django 6.0.3 on 2026-03-29 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('Sid', models.AutoField(primary_key=True, serialize=False)),
                ('S_name', models.CharField(max_length=255, null=True)),
                ('S_pic_url', models.CharField(max_length=255, null=True)),
                ('S_Introduce', models.TextField(null=True)),
            ],
            options={
                'db_table': 'snack',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('Cid', models.AutoField(primary_key=True, serialize=False)),
                ('Cname', models.CharField(max_length=10, unique=True)),
                ('Cum_X', models.IntegerField()),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('Uname', models.CharField(max_length=20, unique=True)),
                ('Uemail', models.CharField(max_length=255, null=True)),
                ('Upwd', models.CharField(max_length=16)),
                ('jurisdiction', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ScenicZone',
            fields=[
                ('SZid', models.AutoField(primary_key=True, serialize=False)),
                ('SZ_name', models.CharField(max_length=50, null=True)),
                ('SZ_message', models.IntegerField(null=True)),
                ('SZ_score', models.FloatField(null=True)),
                ('SZ_popularity', models.IntegerField(null=True)),
                ('SZ_address', models.TextField(null=True)),
                ('SZ_time', models.CharField(max_length=100, null=True)),
                ('SZ_introduce', models.TextField(null=True)),
                ('SZ_pic_url', models.CharField(max_length=255, null=True)),
                ('SZ_sIntroduce', models.TextField(null=True)),
                ('SZ_city', models.ForeignKey(db_column='SZ_city', null=True, on_delete=django.db.models.deletion.RESTRICT, to='tweb.city', to_field='Cname')),
            ],
            options={
                'db_table': 'scenic_zone',
            },
        ),
    ]
