# Generated by Django 6.0.3 on 2026-03-29 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CID', models.AutoField(primary_key=True, serialize=False)),
                ('C_scenic_name', models.CharField(max_length=100)),
                ('C_content', models.TextField()),
                ('C_time', models.DateTimeField(auto_now_add=True)),
                ('C_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tweb.user')),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['-C_time'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('FID', models.AutoField(primary_key=True, serialize=False)),
                ('F_scenic_name', models.CharField(max_length=100)),
                ('F_pic_url', models.CharField(max_length=255, null=True)),
                ('F_time', models.DateTimeField(auto_now_add=True)),
                ('F_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='tweb.user')),
            ],
            options={
                'db_table': 'favorite',
                'ordering': ['-F_time'],
            },
        ),
    ]
