# Generated by Django 6.0.3 on 2026-03-29 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweb', '0003_user_avatar_user_birthday_user_gender_user_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('HID', models.AutoField(primary_key=True, serialize=False)),
                ('H_name', models.CharField(max_length=100)),
                ('H_province', models.CharField(max_length=50, null=True)),
                ('H_city', models.CharField(max_length=50, null=True)),
                ('H_address', models.CharField(max_length=255, null=True)),
                ('H_score', models.FloatField(default=4.0)),
                ('H_price', models.IntegerField(null=True)),
                ('H_rooms', models.IntegerField(default=10)),
                ('H_pic_url', models.CharField(max_length=500, null=True)),
                ('H_introduce', models.TextField(null=True)),
                ('H_tel', models.CharField(max_length=50, null=True)),
                ('H_type', models.CharField(max_length=50, null=True)),
                ('H_star', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'hotel',
                'ordering': ['-H_score', '-HID'],
            },
        ),
        migrations.CreateModel(
            name='HotelComment',
            fields=[
                ('HCID', models.AutoField(primary_key=True, serialize=False)),
                ('HC_hotel_name', models.CharField(max_length=100)),
                ('HC_content', models.TextField()),
                ('HC_time', models.DateTimeField(auto_now_add=True)),
                ('HC_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_comments', to='tweb.user')),
            ],
            options={
                'db_table': 'hotel_comment',
                'ordering': ['-HC_time'],
            },
        ),
        migrations.CreateModel(
            name='HotelFavorite',
            fields=[
                ('HFID', models.AutoField(primary_key=True, serialize=False)),
                ('HF_hotel_name', models.CharField(max_length=100)),
                ('HF_pic_url', models.CharField(max_length=255, null=True)),
                ('HF_time', models.DateTimeField(auto_now_add=True)),
                ('HF_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_favorites', to='tweb.user')),
            ],
            options={
                'db_table': 'hotel_favorite',
                'ordering': ['-HF_time'],
            },
        ),
    ]
