# Generated by Django 6.0.3 on 2026-03-29 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweb', '0004_hotel_hotelcomment_hotelfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOrder',
            fields=[
                ('OID', models.AutoField(primary_key=True, serialize=False)),
                ('O_hotel_name', models.CharField(max_length=100)),
                ('O_hotel_pic', models.CharField(max_length=500, null=True)),
                ('O_hotel_address', models.CharField(max_length=255, null=True)),
                ('O_hotel_tel', models.CharField(max_length=50, null=True)),
                ('O_checkin_date', models.DateField()),
                ('O_checkout_date', models.DateField()),
                ('O_room_count', models.IntegerField(default=1)),
                ('O_room_type', models.CharField(max_length=50, null=True)),
                ('O_total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('O_payment_method', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('bankcard', '银行卡')], default='alipay', max_length=20)),
                ('O_status', models.CharField(choices=[('paid', '已支付'), ('cancelled', '已取消')], default='paid', max_length=20)),
                ('O_create_time', models.DateTimeField(auto_now_add=True)),
                ('O_cancel_time', models.DateTimeField(blank=True, null=True)),
                ('O_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_orders', to='tweb.user')),
            ],
            options={
                'db_table': 'hotel_order',
                'ordering': ['-O_create_time'],
            },
        ),
    ]
