# Generated by Django 6.0.3 on 2026-03-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweb', '0005_hotelorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelorder',
            name='O_hotel_tel',
        ),
    ]
